spring:
  h2:
    console.path: /console
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./bazaDanych
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
logging:
  level:
    org:
      springframework:
        security: debug